/**
 * MCP Tools: read-only access to portal-internal task/project state.
 *
 * Backed by the general dispatch system (Task / TaskLog / Project /
 * AgentProfile). The AmonisTask schema has no projectId, so it can't
 * satisfy the spec'd output shape — these tools expose the dispatcher
 * tasks instead, which is what the AI assistant actually needs to track.
 */

import prisma from '@/lib/db';
import type { McpToolDef } from './registry';

export const portalTools: McpToolDef[] = [
  {
    name: 'portal_get_task',
    description:
      'Fetch a dispatched task with its project, agent, and the last 50 log lines (oldest first).',
    inputSchema: {
      type: 'object',
      properties: {
        task_id: { type: 'string', description: 'Task UUID' },
      },
      required: ['task_id'],
    },
    adminOnly: false,
    handler: async (input) => {
      const taskId = typeof input.task_id === 'string' ? input.task_id : '';
      if (!taskId) return { error: 'task_id required' };

      const task = await prisma.task.findUnique({
        where: { id: taskId },
        select: {
          id: true,
          title: true,
          status: true,
          resultType: true,
          resultUrl: true,
          resultSummary: true,
          errorMessage: true,
          createdAt: true,
          completedAt: true,
          project: { select: { name: true } },
          agentProfile: { select: { name: true } },
        },
      });
      if (!task) return { error: 'not found' };

      const recent = await prisma.taskLog.findMany({
        where: { taskId },
        orderBy: { createdAt: 'desc' },
        take: 50,
        select: { level: true, message: true, createdAt: true },
      });
      const logs = recent.reverse().map((l) => ({
        level: l.level,
        message: l.message,
        timestamp: l.createdAt.toISOString(),
      }));

      return {
        id: task.id,
        title: task.title,
        status: task.status,
        projectName: task.project.name,
        agentName: task.agentProfile?.name ?? null,
        createdAt: task.createdAt.toISOString(),
        completedAt: task.completedAt?.toISOString() ?? null,
        output: task.resultSummary ?? task.errorMessage ?? '',
        prUrl: task.resultType === 'pr' ? task.resultUrl : null,
        // Branch name is generated by the worker at runtime and not
        // persisted on the task row, so we can't recover it after the fact.
        branchName: null,
        logs,
      };
    },
  },

  {
    name: 'portal_list_tasks',
    description: 'List dispatched tasks, optionally filtered by status or project slug.',
    inputSchema: {
      type: 'object',
      properties: {
        status: {
          type: 'string',
          description: 'pending | queued | in_progress | needs_review | completed | failed | cancelled',
        },
        project_slug: { type: 'string', description: 'Project slug to filter by' },
        limit: { type: 'number', description: 'Max rows (default 20, max 100)' },
      },
    },
    adminOnly: false,
    handler: async (input) => {
      const limit = Math.min(
        Math.max(typeof input.limit === 'number' ? input.limit : 20, 1),
        100
      );
      const where: { status?: string; project?: { slug: string } } = {};
      if (typeof input.status === 'string' && input.status) where.status = input.status;
      if (typeof input.project_slug === 'string' && input.project_slug) {
        where.project = { slug: input.project_slug };
      }

      const tasks = await prisma.task.findMany({
        where,
        orderBy: { createdAt: 'desc' },
        take: limit,
        select: {
          id: true,
          title: true,
          status: true,
          createdAt: true,
          project: { select: { name: true } },
          agentProfile: { select: { name: true } },
        },
      });
      return tasks.map((t) => ({
        id: t.id,
        title: t.title,
        status: t.status,
        projectName: t.project.name,
        agentName: t.agentProfile?.name ?? null,
        createdAt: t.createdAt.toISOString(),
      }));
    },
  },

  {
    name: 'portal_get_project',
    description: 'Fetch a project by slug, with counts of its tasks and sessions.',
    inputSchema: {
      type: 'object',
      properties: {
        slug: { type: 'string', description: 'Project slug' },
      },
      required: ['slug'],
    },
    adminOnly: false,
    handler: async (input) => {
      const slug = typeof input.slug === 'string' ? input.slug : '';
      if (!slug) return { error: 'slug required' };

      const project = await prisma.project.findUnique({
        where: { slug },
        select: {
          name: true,
          slug: true,
          status: true,
          repoUrl: true,
          description: true,
          _count: { select: { tasks: true, sessions: true } },
        },
      });
      if (!project) return { error: 'not found' };

      return {
        name: project.name,
        slug: project.slug,
        status: project.status,
        // No `kind` column on Project — spec field returned as null.
        kind: null,
        repoUrl: project.repoUrl,
        description: project.description,
        _count: project._count,
      };
    },
  },
];
